name = "contact-worker"
main = "src/index.ts"
compatibility_date = "2024-05-24"

# Configuration for production
[vars]
ALLOWED_ORIGIN = "https://jeshuasalazar.com"
# Turnstile site key (public)
TURNSTILE_SITE_KEY = "1x00000000000000000000AA" # Replace with your real Turnstile Site Key (always passes in test)
# Send email notification to:
CONTACT_TO = "hola@jeshuasalazar.com"
# Send email from (must be validated in Resend):
CONTACT_FROM = "hola@jeshuasalazar.com"
